export class MessageTypes {
    constructor() {
        this.messageTypes = [
            {'msgType':'0','description':'Heartbeat'},
            {'msgType':'1','description':'Test Request'},
            {'msgType':'2','description':'Resend Request'},
            {'msgType':'3','description':'Reject'},
            {'msgType':'4','description':'Sequence Reset'},
            {'msgType':'5','description':'Logout'},
            {'msgType':'6','description':'Indication of Interest'},
            {'msgType':'7','description':'Advertisement'},
            {'msgType':'8','description':'Execution Report'},
            {'msgType':'9','description':'Order Cancel Reject'},
            {'msgType':'a','description':'Quote Status Request'},
            {'msgType':'A','description':'Logon'},
            {'msgType':'AA','description':'Derivative Security List'},
            {'msgType':'AB','description':'New Order - Multileg'},
            {'msgType':'AC','description':'Multileg Order Cancel/Replace (a.k.a. Multileg Order Modification Request)'},
            {'msgType':'AD','description':'Trade Capture Report Request'},
            {'msgType':'AE','description':'Trade Capture Report'},
            {'msgType':'AF','description':'Order Mass Status Request'},
            {'msgType':'AG','description':'Quote Request Reject'},
            {'msgType':'AH','description':'RFQ Request'},
            {'msgType':'AI','description':'Quote Status Report'},
            {'msgType':'AJ','description':'Quote Response'},
            {'msgType':'AK','description':'Confirmation'},
            {'msgType':'AL','description':'Position Maintenance Request'},
            {'msgType':'AM','description':'Position Maintenance Report'},
            {'msgType':'AN','description':'Request For Positions'},
            {'msgType':'AO','description':'Request For Positions Ack'},
            {'msgType':'AP','description':'Position Report'},
            {'msgType':'AQ','description':'Trade Capture Report Request Ack'},
            {'msgType':'AR','description':'Trade Capture Report Ack'},
            {'msgType':'AS','description':'Allocation Report (a.k.a. Allocation Claim)'},
            {'msgType':'AT','description':'Allocation Report Ack (a.k.a. Allocation Claim Ack)'},
            {'msgType':'AU','description':'Confirmation Ack (a.k.a. Affirmation)'},
            {'msgType':'AV','description':'Settlement Instruction Request'},
            {'msgType':'AW','description':'Assignment Report'},
            {'msgType':'AX','description':'Collateral Request'},
            {'msgType':'AY','description':'Collateral Assignment'},
            {'msgType':'AZ','description':'Collateral Response'},
            {'msgType':'B','description':'News'},
            {'msgType':'b','description':'Mass Quote Acknowledgement'},
            {'msgType':'BA','description':'Collateral Report'},
            {'msgType':'BB','description':'Collateral Inquiry'},
            {'msgType':'BC','description':'Network Counterparty System Status Request'},
            {'msgType':'BD','description':'Network Counterparty System Status Response'},
            {'msgType':'BE','description':'User Request'},
            {'msgType':'BF','description':'User Response'},
            {'msgType':'BG','description':'Collateral Inquiry Ack'},
            {'msgType':'BH','description':'Confirmation Request'},
            {'msgType':'C','description':'Email'},
            {'msgType':'c','description':'Security Definition Request'},
            {'msgType':'d','description':'Security Definition'},
            {'msgType':'D','description':'New Order - Single'},
            {'msgType':'e','description':'Security Status Request'},
            {'msgType':'E','description':'New Order - List'},
            {'msgType':'F','description':'Order Cancel Request'},
            {'msgType':'f','description':'Security Status'},
            {'msgType':'G','description':'Order Cancel/Replace Request (a.k.a. Order Modification Request)'},
            {'msgType':'g','description':'Trading Session Status Request'},
            {'msgType':'H','description':'Order Status Request'},
            {'msgType':'h','description':'Trading Session Status'},
            {'msgType':'i','description':'Mass Quote'},
            {'msgType':'j','description':'Business Message Reject'},
            {'msgType':'J','description':'Allocation Instruction'},
            {'msgType':'k','description':'Bid Request'},
            {'msgType':'K','description':'List Cancel Request'},
            {'msgType':'l','description':'Bid Response (lowercase L)'},
            {'msgType':'L','description':'List Execute'},
            {'msgType':'m','description':'List Strike Price'},
            {'msgType':'M','description':'List Status Request'},
            {'msgType':'n','description':'XML message (e.g. non FIX Msg Type)'},
            {'msgType':'N','description':'List Status'},
            {'msgType':'o','description':'Registration Instructions'},
            {'msgType':'p','description':'Registration Instructions Response'},
            {'msgType':'P','description':'Allocation Instruction Ack'},
            {'msgType':'q','description':'Order Mass Cancel Request'},
            {'msgType':'Q','description':'don\'t Know Trade (DK)'},
            {'msgType':'R','description':'Quote Request'},
            {'msgType':'r','description':'Order Mass Cancel Report'},
            {'msgType':'S','description':'Quote'},
            {'msgType':'s','description':'New Order - Cross'},
            {'msgType':'T','description':'Settlement Instructions'},
            {'msgType':'t','description':'Cross Order Cancel/Replace Request (a.k.a. Cross Order Modification Request)'},
            {'msgType':'u','description':'Cross Order Cancel Request'},
            {'msgType':'V','description':'Market Data Request'},
            {'msgType':'v','description':'Security Type Request'},
            {'msgType':'w','description':'Security Types'},
            {'msgType':'W','description':'Market Data - Snapshot/Full Refresh'},
            {'msgType':'x','description':'Security List Request'},
            {'msgType':'X','description':'Market Data - Incremental Refresh'},
            {'msgType':'Y','description':'Market Data Request Reject'},
            {'msgType':'y','description':'Security List'},
            {'msgType':'Z','description':'Quote Cancel'},
            {'msgType':'z','description':'Derivative Security List Request'},
            {'msgType':'BO','description':'Contrary Intention Report'},
            {'msgType':'BP','description':'Security Definition Update Report'},
            {'msgType':'BK','description':'Security List Update Report'},
            {'msgType':'BL','description':'Adjusted Position Report'},
            {'msgType':'BM','description':'Allocation Instruction Alert'},
            {'msgType':'BN','description':'Execution Acknowledgement'},
            {'msgType':'BJ','description':'Trading Session List'},
            {'msgType':'BI','description':'Trading Session List Request'}
        ];
    }

    find(messageType) {
        return this.messageTypes.find(item => item.msgType === messageType);
    }

    process(item, tag, value) {
        if(tag === 35 || tag === 372) {
            let messageType = this.find(value);
            if(messageType) {
                item.messageTypeDetail = messageType;
            }
        }
    }
}